### ISSUE TITLE
how to `nix build` vulnxscan?

### ISSUE THREAD

**Issue by lestephane** [tiiuae/sbomnix#51]
`nix build .#sbomnix` works fine

but `nix build .#vulnxscan` gives 

```
does not provide attribute 'packages.x86_64-linux.vulnxscan', 'legacyPackages.x86_64-linux.vulnxscan' or 'vulnxscan'
```

I see in the `flake.nix` that vulnxscan is an `app`. And it is clear to me than an app is meant to be `nix run`-d.

Except that if I run it this way, no gc root is created, and after reboot, all the derivations are gone, and I have to go make coffee while the run command fetches everything again. In my testing, only actually building the app/package will cause a gc root to be created, thereby caching the derivation. 

Sorry if this is a stupid question, nix has been just head banging from the get go for me, I've only started using it over the weekend.

**Comment by henrirosten** [comment]
Hello, maybe this helps:

```bash
$ git clone https://github.com/tiiuae/sbomnix
$ cd sbomnix
$ nix build

# Above command generates the executable 'result/bin/vulnxscan':
$ result/bin/vulnxscan --help
```

**Comment by lestephane** [comment]
> ```shell
> # Above command generates the executable 'result/bin/vulnxscan':
> $ result/bin/vulnxscan --help
> ```

`nix build` without any argument fails in the version i have (nix-bin 2.6.0)

```
does not provide attribute 'packages.x86_64-linux.defaultPackage.x86_64-linux', 'legacyPackages.x86_64-linux.defaultPackage.x86_64-linux' or 'defaultPackage.x86_64-linux'
```

But `nix build .#sbomnix` actually builds all the apps under the result directory

```
$ ls result/bin/
nixgraph  osv.py  sbomnix  update-cpedict.sh  vulnxscan
```

So that's how I can build vulnxscan. Issue closed.
