### ISSUE TITLE
improve the way sbomnix reads pacakge metadata

### ISSUE THREAD

**Issue by henrirosten** [tiiuae/sbomnix#62]
sbomnix reads the nix package meta info from the json file given via the command-line `--meta` option.

This needs to be re-done properly, ultimately aiming to get rid of the need for `--meta` command line argument completely.

**Comment by henrirosten** [comment]
@domenkozar : thanks for providing input to this issue!

You are proposing to change this in nixpkgs, right?

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/256296
